version: '3.8'

services:
  node-app:
    build: .
    container_name: node_container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=3000
    restart: always
