version: '3.8'

services:
  app:
    image: node:14
    container_name: node_app
    working_dir: /app
    volumes:
      - ./app:/app
    command: ["node", "app.js"]
    depends_on:
      - mongo
    networks:
      - app_network
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - ./data/db:/data/db
    networks:
      - app_network
    ports:
      - "27017:27017"

networks:
  app_network:
    driver: bridge
